services:
  dashboard-db:
    image: postgres:latest
    container_name: dashboard-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: analyticsDatabase
    ports:
      - '5400:5432'

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 3

  localstack:
    container_name: localstack
    image: localstack/localstack:3.6.0
    ports:
      - '4566:4566'
      - '4572:4572'
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
      - ./scripts/s3_demo_bucket_init.sh:/etc/localstack/init/ready.d/localstack-init.sh

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
      
  datadog-agent:
    container_name: datadog-agent
    image: datadog/agent:7.64.3
    restart: unless-stopped
    environment:
      - DD_SITE=${DD_SITE}
      - DD_API_KEY=${DD_API_KEY}   
      - DD_SERVICE=${DD_SERVICE}    
      - DD_VERSION=${DD_VERSION}
      - DD_ENV=${DD_ENV}
      - DD_TAGS=${DD_TAGS}
      - DD_APM_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_RUNTIME_METRICS_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - '8125:8125/udp'
      - '8126:8126'

volumes:
  postgres_data:
  localstack_data:
