type PageConfig = {
    [key: string]: string[];
  };
  
export const pageConfig: PageConfig = {
    "revive": [
        "/",
        "/dashboard",
        "/chats",
        "/unanswered-questions",
        "/knowledge",
        "/admin",
        "/security-violation-messages",
        "/message-rating",
        "/feedback",
    ],
    "glidepath": [
        "/",
        "/dashboard",
        "/chats",
        "/unanswered-questions",
        "/knowledge",
        "/admin",
        "/security-violation-messages",
        "/message-rating",
        "/feedback",
    ],
    "ntrustus": [
        "/",
        "/dashboard",
        "/chats",
        "/unanswered-questions",
        "/knowledge",
        "/admin",
        "/security-violation-messages",
        "/message-rating",
        "/feedback",
    ],
    "service_seeking": [
        "/",
        "/dashboard",
        "/chats",
        "/unanswered-questions",
        "/knowledge",
        "/admin",
        "/security-violation-messages",
        "/message-rating",
        "/feedback",
    ],
    "service-seeking": [
        "/",
        "/dashboard",
        "/chats",
        "/unanswered-questions",
        "/knowledge",
        "/admin",
        "/security-violation-messages",
        "/message-rating",
        "/feedback",
    ],
    "bruntwork": [
        "/",
        "/dashboard",
        "/chats",
        "/completed-sessions",
        "/unanswered-questions",
        "/knowledge",
        "/admin",
        "/security-violation-messages",
        "/message-rating",
        "/feedback",
    ],
    "meir": [
        "/",
        "/dashboard",
        "/chats",
        "/unanswered-questions",
        "/knowledge",
        "/admin",
        "/security-violation-messages",
        "/message-rating",
        "/feedback",
    ],
    "test-company": [
        "/",
        "/dashboard",
        "/analytics",
        "/chats",
        "/batch",
        "/settings",
        "/live-chat",
        "/unanswered-questions",
        "/knowledge",
        "/message-rating",
        "/admin",
        "/completed-sessions",
        "/security-violation-messages",
        "/feedback",
        "/superset-analytics",
    ]
};