version: '3.7'

services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - "5433:5432"
    volumes:
      - superset_db_home:/var/lib/postgresql/data

  superset:
    build: .
    container_name: superset_app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      # Database
      DATABASE_DIALECT: postgresql
      DATABASE_USER: ${POSTGRES_USER:-superset}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-superset}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: ${POSTGRES_DB:-superset}
      
      # Redis
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      
      # Superset specific config
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY:-your-secret-key-here}
      SUPERSET_WEBSERVER_HOST: 0.0.0.0
      SUPERSET_WEBSERVER_PORT: 8088
      
      # CORS configuration from env
      CORS_ORIGINS: ${CORS_ORIGINS:-"http://localhost:3000,http://localhost:5173"}
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username ${SUPERSET_ADMIN_USERNAME:-admin} --firstname Admin --lastname User --email admin@superset.com --password ${SUPERSET_ADMIN_PASSWORD:-admin} &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "

volumes:
  superset_db_home:
    driver: local
  superset_home:
    driver: local