name: SonarQube Scanner

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']
    
jobs:
  sonarqube-scan:
    name: SonarQube Static Code Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: SonarQube Static Code Analysis
        uses: insait-io/github-actions/.github/actions/sonarqube@main
        with:
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_BRANCH: ${{ github.ref_name != 'main' && github.ref_name || '' }}
          SONAR_PR_KEY: ${{ github.event.pull_request.number }}
          SONAR_PR_BRANCH: ${{ github.head_ref }}
          SONAR_PR_BASE: ${{ github.base_ref }}